### PR TITLE
Add do_ping for sqlalchemy_rqlite dialect

### PR DESCRIPTION
**Pull request by 0x0101010**
add do_ping for sqlalchemy create_engin.pool_pre_ping to check connection is active

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks for your contribution -- is this a standard method that SQL Alchemy dialects implement?

**Comment by 0x0101010** [comment]
> Thanks for your contribution -- is this a standard method that SQL Alchemy dialects implement?

yes, other  sqlalchemy dialects implement the do_ping method
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/mysqldb.py

as the sqlalchemy document states that the purpose of the pool_pre_ping parameter is to check the connection, to implement this function. So sqlalchemy_rqlite needs to add do_ping method in sqlalchem_rqlite and pyrqlite needs to add ping method. 
https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.Pool.params.pre_ping

related issue https://github.com/rqlite/sqlalchemy-rqlite/issues/4

please review the pyrqlite changes
https://github.com/rqlite/pyrqlite/pull/50

thanks

**Comment by otoolep** [comment]
OK, thank you. Other PR is ready to merge, right? If so, I'll do that, then merge this.

**Comment by 0x0101010** [comment]
> OK, thank you. Other PR is ready to merge, right? If so, I'll do that, then merge this.
yes, that's right

**Pull request merged**
